name: Run tests
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version-file: .python-version
      - run: |
          make install
      - name: Check style format
        run: black --check .
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.14.2'
          cache: 'npm'
      - name: Install Node.js dependencies
        run: |
          npm ci
          npm install -g ganache-cli
      - name: Run tests
        run: brownie test -s
